server:
  port: 9906
  servlet:
    context-path: /tempRegister
  tomcat:
    uri-encoding: UTF-8
    max-connections: 10000
    threads:
      max: 1000
  compression:
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
spring:
  datasource:
    url: jdbc:mysql://192.168.1.210:3306/jd_triage?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 500
      max-lifetime: 60000
      minimum-idle: 20
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        enable_lazy_load_no_trans: true
      open-in-view: false
  redis:
    host: 192.168.1.210
    port: 6379
    password:
    connect-timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
    database: 0
  web:
    resources:
      static-locations: classpath:/static/
logging:
  file:
    name: logs/delay_std.log